export const COLUNAS = [
  { key: 'check', label: '✔', width: 40, align: 'center', type: 'checkbox', sortable: false },
  { key: 'entrada', label: 'ENT', width: 75, align: 'left', type: 'date', sortable: true },
  { key: 'remarcacao', label: 'REM', width: 75, align: 'left', type: 'date', sortable: true },
  { key: 'id', label: 'CÓDIGO', width: 80, align: 'left', type: 'text', sortable: true },
  { key: 'descricao', label: 'DESCRIÇÃO', width: 250, align: 'left', type: 'text', sortable: true },
  { key: 'quantidade', label: 'QUAN', width: 60, align: 'right', type: 'number', sortable: true },
  { key: 'unidade', label: 'UND', width: 50, align: 'center', type: 'text', sortable: true },
  { key: 'lista', label: 'P. LISTA', width: 80, align: 'right', type: 'currency', sortable: true },
  { key: 'icms', label: 'ICMS', width: 60, align: 'right', type: 'percent', sortable: true },
  { key: 'outros', label: 'OUTROS', width: 70, align: 'right', type: 'currency', sortable: true },
  { key: 'frete', label: 'FRETE', width: 70, align: 'right', type: 'currency', sortable: true },
  { key: 'custo', label: 'P. CUSTO', width: 90, align: 'right', type: 'editable-currency', sortable: true },
  { key: 'sugerido', label: 'P. SUGER', width: 90, align: 'right', type: 'editable-currency', sortable: true },
  { key: 'atual', label: 'P. ATUAL', width: 90, align: 'right', type: 'editable-currency', sortable: true },
  { key: 'markupReal', label: 'MKP REAL', width: 80, align: 'right', type: 'percent-1', sortable: true },
  { key: 'markup', label: 'MKP CAD', width: 80, align: 'right', type: 'editable-percent-1', sortable: true },
  { key: 'difMarkup', label: 'DIF MKP', width: 80, align: 'right', type: 'tag', sortable: true },
  { key: 'conversao', label: 'CONV', width: 60, align: 'right', type: 'number', sortable: true },
];